package com.nightonke.boommenu;

import com.nightonke.boommenu.Types.PlaceType;
import java.lang.reflect.Array;

public class EndLocationsFactory {
    public static int[][] getEndLocations(PlaceType placeType, int screenWidth, int screenHeight, int buttonWidth, int buttonHeight) {
        int[][] endLocations = (int[][]) Array.newInstance(Integer.TYPE, new int[]{9, 2});
        if (placeType.equals(PlaceType.CIRCLE_1_1)) {
            endLocations[0][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[0][1] = (screenHeight / 2) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_2_1)) {
            endLocations[0][0] = (screenWidth / 3) - (buttonWidth / 2);
            endLocations[0][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[1][0] = ((screenWidth * 2) / 3) - (buttonWidth / 2);
            endLocations[1][1] = (screenHeight / 2) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_2_2)) {
            endLocations[0][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[0][1] = (screenHeight / 3) - (buttonWidth / 2);
            endLocations[1][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[1][1] = ((screenHeight * 2) / 3) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_3_1)) {
            int dis = (buttonWidth * 9) / 8;
            endLocations[0][0] = ((screenWidth / 2) - dis) - (buttonWidth / 2);
            endLocations[0][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[1][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[1][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[2][0] = ((screenWidth / 2) + dis) - (buttonWidth / 2);
            endLocations[2][1] = (screenHeight / 2) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_3_2)) {
            int dis2 = (buttonWidth * 9) / 8;
            endLocations[0][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[0][1] = ((screenHeight / 2) - dis2) - (buttonWidth / 2);
            endLocations[1][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[1][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[2][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[2][1] = ((screenHeight / 2) + dis2) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_3_3)) {
            int b = screenWidth / 6;
            int c = (int) (((double) (b * 2)) / Math.sqrt(3.0d));
            int a = c / 2;
            endLocations[0][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[0][1] = ((screenHeight / 2) - c) - (buttonWidth / 2);
            endLocations[1][0] = ((screenWidth / 2) - b) - (buttonWidth / 2);
            endLocations[1][1] = ((screenHeight / 2) + a) - (buttonWidth / 2);
            endLocations[2][0] = ((screenWidth / 2) + b) - (buttonWidth / 2);
            endLocations[2][1] = ((screenHeight / 2) + a) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_3_4)) {
            int b2 = screenWidth / 6;
            int c2 = (int) (((double) (b2 * 2)) / Math.sqrt(3.0d));
            int a2 = c2 / 2;
            endLocations[0][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[0][1] = ((screenHeight / 2) + c2) - (buttonWidth / 2);
            endLocations[1][0] = ((screenWidth / 2) - b2) - (buttonWidth / 2);
            endLocations[1][1] = ((screenHeight / 2) - a2) - (buttonWidth / 2);
            endLocations[2][0] = ((screenWidth / 2) + b2) - (buttonWidth / 2);
            endLocations[2][1] = ((screenHeight / 2) - a2) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_4_1)) {
            endLocations[0][0] = (screenWidth / 3) - (buttonWidth / 2);
            endLocations[0][1] = ((screenHeight / 2) - (screenWidth / 6)) - (buttonWidth / 2);
            endLocations[1][0] = ((screenWidth * 2) / 3) - (buttonWidth / 2);
            endLocations[1][1] = ((screenHeight / 2) - (screenWidth / 6)) - (buttonWidth / 2);
            endLocations[2][0] = (screenWidth / 3) - (buttonWidth / 2);
            endLocations[2][1] = ((screenHeight / 2) + (screenWidth / 6)) - (buttonWidth / 2);
            endLocations[3][0] = ((screenWidth * 2) / 3) - (buttonWidth / 2);
            endLocations[3][1] = ((screenHeight / 2) + (screenWidth / 6)) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_4_2)) {
            double s2 = Math.sqrt(2.0d);
            endLocations[0][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[0][1] = (int) ((((double) (screenHeight / 2)) - (((double) (screenWidth / 3)) / s2)) - ((double) (buttonWidth / 2)));
            endLocations[1][0] = (int) ((((double) (screenWidth / 2)) + (((double) (screenWidth / 3)) / s2)) - ((double) (buttonWidth / 2)));
            endLocations[1][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[2][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[2][1] = (int) ((((double) (screenHeight / 2)) + (((double) (screenWidth / 3)) / s2)) - ((double) (buttonWidth / 2)));
            endLocations[3][0] = (int) ((((double) (screenWidth / 2)) - (((double) (screenWidth / 3)) / s2)) - ((double) (buttonWidth / 2)));
            endLocations[3][1] = (screenHeight / 2) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_5_1)) {
            double s3 = Math.sqrt(3.0d);
            int h = screenHeight / 2;
            endLocations[0][0] = (screenWidth / 4) - (buttonWidth / 2);
            endLocations[0][1] = h - (buttonWidth / 2);
            endLocations[1][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[1][1] = h - (buttonWidth / 2);
            endLocations[2][0] = ((screenWidth * 3) / 4) - (buttonWidth / 2);
            endLocations[2][1] = h - (buttonWidth / 2);
            endLocations[3][0] = ((screenWidth * 3) / 8) - (buttonWidth / 2);
            endLocations[3][1] = (int) ((((double) h) + ((s3 / 8.0d) * ((double) screenWidth))) - ((double) (buttonWidth / 2)));
            endLocations[4][0] = ((screenWidth * 5) / 8) - (buttonWidth / 2);
            endLocations[4][1] = (int) ((((double) h) + ((s3 / 8.0d) * ((double) screenWidth))) - ((double) (buttonWidth / 2)));
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_5_2)) {
            double s32 = Math.sqrt(3.0d);
            int h2 = screenHeight / 2;
            endLocations[0][0] = ((screenWidth * 3) / 8) - (buttonWidth / 2);
            endLocations[0][1] = h2 - (buttonWidth / 2);
            endLocations[1][0] = ((screenWidth * 5) / 8) - (buttonWidth / 2);
            endLocations[1][1] = h2 - (buttonWidth / 2);
            endLocations[2][0] = (screenWidth / 4) - (buttonWidth / 2);
            endLocations[2][1] = (int) ((((double) h2) + ((s32 / 8.0d) * ((double) screenWidth))) - ((double) (buttonWidth / 2)));
            endLocations[3][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[3][1] = (int) ((((double) h2) + ((s32 / 8.0d) * ((double) screenWidth))) - ((double) (buttonWidth / 2)));
            endLocations[4][0] = ((screenWidth * 3) / 4) - (buttonWidth / 2);
            endLocations[4][1] = (int) ((((double) h2) + ((s32 / 8.0d) * ((double) screenWidth))) - ((double) (buttonWidth / 2)));
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_5_3)) {
            int dis3 = (int) (((double) ((buttonWidth * 9) / 8)) / Math.sqrt(2.0d));
            endLocations[0][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[0][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[1][0] = ((screenWidth / 2) - dis3) - (buttonWidth / 2);
            endLocations[1][1] = ((screenHeight / 2) - dis3) - (buttonWidth / 2);
            endLocations[2][0] = ((screenWidth / 2) + dis3) - (buttonWidth / 2);
            endLocations[2][1] = ((screenHeight / 2) - dis3) - (buttonWidth / 2);
            endLocations[3][0] = ((screenWidth / 2) - dis3) - (buttonWidth / 2);
            endLocations[3][1] = ((screenHeight / 2) + dis3) - (buttonWidth / 2);
            endLocations[4][0] = ((screenWidth / 2) + dis3) - (buttonWidth / 2);
            endLocations[4][1] = ((screenHeight / 2) + dis3) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_5_4)) {
            int dis4 = (buttonWidth * 9) / 8;
            endLocations[0][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[0][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[1][0] = ((screenWidth / 2) - dis4) - (buttonWidth / 2);
            endLocations[1][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[2][0] = ((screenWidth / 2) + dis4) - (buttonWidth / 2);
            endLocations[2][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[3][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[3][1] = ((screenHeight / 2) - dis4) - (buttonWidth / 2);
            endLocations[4][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[4][1] = ((screenHeight / 2) + dis4) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_6_1)) {
            int dis1 = (buttonWidth * 9) / 8;
            int dis22 = (buttonWidth * 9) / 16;
            endLocations[0][0] = ((screenWidth / 2) - dis1) - (buttonWidth / 2);
            endLocations[0][1] = ((screenHeight / 2) - dis22) - (buttonWidth / 2);
            endLocations[1][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[1][1] = ((screenHeight / 2) - dis22) - (buttonWidth / 2);
            endLocations[2][0] = ((screenWidth / 2) + dis1) - (buttonWidth / 2);
            endLocations[2][1] = ((screenHeight / 2) - dis22) - (buttonWidth / 2);
            endLocations[3][0] = ((screenWidth / 2) - dis1) - (buttonWidth / 2);
            endLocations[3][1] = ((screenHeight / 2) + dis22) - (buttonWidth / 2);
            endLocations[4][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[4][1] = ((screenHeight / 2) + dis22) - (buttonWidth / 2);
            endLocations[5][0] = ((screenWidth / 2) + dis1) - (buttonWidth / 2);
            endLocations[5][1] = ((screenHeight / 2) + dis22) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_6_2)) {
            int dis12 = (buttonWidth * 9) / 8;
            int dis23 = (buttonWidth * 9) / 16;
            endLocations[0][0] = ((screenWidth / 2) - dis23) - (buttonWidth / 2);
            endLocations[0][1] = ((screenHeight / 2) - dis12) - (buttonWidth / 2);
            endLocations[1][0] = ((screenWidth / 2) + dis23) - (buttonWidth / 2);
            endLocations[1][1] = ((screenHeight / 2) - dis12) - (buttonWidth / 2);
            endLocations[2][0] = ((screenWidth / 2) - dis23) - (buttonWidth / 2);
            endLocations[2][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[3][0] = ((screenWidth / 2) + dis23) - (buttonWidth / 2);
            endLocations[3][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[4][0] = ((screenWidth / 2) - dis23) - (buttonWidth / 2);
            endLocations[4][1] = ((screenHeight / 2) + dis12) - (buttonWidth / 2);
            endLocations[5][0] = ((screenWidth / 2) + dis23) - (buttonWidth / 2);
            endLocations[5][1] = ((screenHeight / 2) + dis12) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_6_3)) {
            int dis13 = (buttonWidth * 9) / 8;
            int dis24 = (int) (((double) (dis13 / 2)) * Math.sqrt(3.0d));
            endLocations[0][0] = ((screenWidth / 2) - dis13) - (buttonWidth / 2);
            endLocations[0][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[1][0] = ((screenWidth / 2) - (dis13 / 2)) - (buttonWidth / 2);
            endLocations[1][1] = ((screenHeight / 2) - dis24) - (buttonWidth / 2);
            endLocations[2][0] = ((screenWidth / 2) + (dis13 / 2)) - (buttonWidth / 2);
            endLocations[2][1] = ((screenHeight / 2) - dis24) - (buttonWidth / 2);
            endLocations[3][0] = ((screenWidth / 2) + dis13) - (buttonWidth / 2);
            endLocations[3][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[4][0] = ((screenWidth / 2) + (dis13 / 2)) - (buttonWidth / 2);
            endLocations[4][1] = ((screenHeight / 2) + dis24) - (buttonWidth / 2);
            endLocations[5][0] = ((screenWidth / 2) - (dis13 / 2)) - (buttonWidth / 2);
            endLocations[5][1] = ((screenHeight / 2) + dis24) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_6_4)) {
            int dis14 = (buttonWidth * 9) / 8;
            int dis25 = (int) (((double) (dis14 / 2)) * Math.sqrt(3.0d));
            endLocations[0][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[0][1] = ((screenHeight / 2) - dis14) - (buttonWidth / 2);
            endLocations[1][0] = ((screenWidth / 2) + dis25) - (buttonWidth / 2);
            endLocations[1][1] = ((screenHeight / 2) - (dis14 / 2)) - (buttonWidth / 2);
            endLocations[2][0] = ((screenWidth / 2) + dis25) - (buttonWidth / 2);
            endLocations[2][1] = ((screenHeight / 2) + (dis14 / 2)) - (buttonWidth / 2);
            endLocations[3][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[3][1] = ((screenHeight / 2) + dis14) - (buttonWidth / 2);
            endLocations[4][0] = ((screenWidth / 2) - dis25) - (buttonWidth / 2);
            endLocations[4][1] = ((screenHeight / 2) + (dis14 / 2)) - (buttonWidth / 2);
            endLocations[5][0] = ((screenWidth / 2) - dis25) - (buttonWidth / 2);
            endLocations[5][1] = ((screenHeight / 2) - (dis14 / 2)) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_6_5)) {
            int dis15 = (buttonWidth * 9) / 16;
            int dis26 = (int) (((double) dis15) * Math.sqrt(3.0d));
            endLocations[0][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[0][1] = ((screenHeight / 2) - dis26) - (buttonWidth / 2);
            endLocations[1][0] = ((screenWidth / 2) - dis15) - (buttonWidth / 2);
            endLocations[1][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[2][0] = ((screenWidth / 2) + dis15) - (buttonWidth / 2);
            endLocations[2][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[3][0] = ((screenWidth / 2) - (dis15 * 2)) - (buttonWidth / 2);
            endLocations[3][1] = ((screenHeight / 2) + dis26) - (buttonWidth / 2);
            endLocations[4][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[4][1] = ((screenHeight / 2) + dis26) - (buttonWidth / 2);
            endLocations[5][0] = ((screenWidth / 2) + (dis15 * 2)) - (buttonWidth / 2);
            endLocations[5][1] = ((screenHeight / 2) + dis26) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_6_6)) {
            int dis16 = (buttonWidth * 9) / 16;
            int dis27 = (int) (((double) dis16) * Math.sqrt(3.0d));
            endLocations[0][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[0][1] = ((screenHeight / 2) + dis27) - (buttonWidth / 2);
            endLocations[1][0] = ((screenWidth / 2) - dis16) - (buttonWidth / 2);
            endLocations[1][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[2][0] = ((screenWidth / 2) + dis16) - (buttonWidth / 2);
            endLocations[2][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[3][0] = ((screenWidth / 2) - (dis16 * 2)) - (buttonWidth / 2);
            endLocations[3][1] = ((screenHeight / 2) - dis27) - (buttonWidth / 2);
            endLocations[4][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[4][1] = ((screenHeight / 2) - dis27) - (buttonWidth / 2);
            endLocations[5][0] = ((screenWidth / 2) + (dis16 * 2)) - (buttonWidth / 2);
            endLocations[5][1] = ((screenHeight / 2) - dis27) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_7_1)) {
            int dis5 = (buttonWidth * 9) / 8;
            endLocations[0][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[0][1] = ((screenHeight / 2) - dis5) - (buttonWidth / 2);
            endLocations[1][0] = ((screenWidth / 2) - dis5) - (buttonWidth / 2);
            endLocations[1][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[2][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[2][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[3][0] = ((screenWidth / 2) + dis5) - (buttonWidth / 2);
            endLocations[3][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[4][0] = ((screenWidth / 2) - dis5) - (buttonWidth / 2);
            endLocations[4][1] = ((screenHeight / 2) + dis5) - (buttonWidth / 2);
            endLocations[5][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[5][1] = ((screenHeight / 2) + dis5) - (buttonWidth / 2);
            endLocations[6][0] = ((screenWidth / 2) + dis5) - (buttonWidth / 2);
            endLocations[6][1] = ((screenHeight / 2) + dis5) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_7_2)) {
            int dis6 = (buttonWidth * 9) / 8;
            endLocations[0][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[0][1] = ((screenHeight / 2) + dis6) - (buttonWidth / 2);
            endLocations[1][0] = ((screenWidth / 2) - dis6) - (buttonWidth / 2);
            endLocations[1][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[2][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[2][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[3][0] = ((screenWidth / 2) + dis6) - (buttonWidth / 2);
            endLocations[3][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[4][0] = ((screenWidth / 2) - dis6) - (buttonWidth / 2);
            endLocations[4][1] = ((screenHeight / 2) - dis6) - (buttonWidth / 2);
            endLocations[5][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[5][1] = ((screenHeight / 2) - dis6) - (buttonWidth / 2);
            endLocations[6][0] = ((screenWidth / 2) + dis6) - (buttonWidth / 2);
            endLocations[6][1] = ((screenHeight / 2) - dis6) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_7_3)) {
            int dis17 = (buttonWidth * 9) / 8;
            int dis28 = (int) (((double) (dis17 / 2)) * Math.sqrt(3.0d));
            endLocations[0][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[0][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[1][0] = ((screenWidth / 2) - dis17) - (buttonWidth / 2);
            endLocations[1][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[2][0] = ((screenWidth / 2) - (dis17 / 2)) - (buttonWidth / 2);
            endLocations[2][1] = ((screenHeight / 2) - dis28) - (buttonWidth / 2);
            endLocations[3][0] = ((screenWidth / 2) + (dis17 / 2)) - (buttonWidth / 2);
            endLocations[3][1] = ((screenHeight / 2) - dis28) - (buttonWidth / 2);
            endLocations[4][0] = ((screenWidth / 2) + dis17) - (buttonWidth / 2);
            endLocations[4][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[5][0] = ((screenWidth / 2) + (dis17 / 2)) - (buttonWidth / 2);
            endLocations[5][1] = ((screenHeight / 2) + dis28) - (buttonWidth / 2);
            endLocations[6][0] = ((screenWidth / 2) - (dis17 / 2)) - (buttonWidth / 2);
            endLocations[6][1] = ((screenHeight / 2) + dis28) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_7_4)) {
            int dis18 = (buttonWidth * 9) / 8;
            int dis29 = (int) (((double) (dis18 / 2)) * Math.sqrt(3.0d));
            endLocations[0][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[0][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[1][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[1][1] = ((screenHeight / 2) - dis18) - (buttonWidth / 2);
            endLocations[2][0] = ((screenWidth / 2) + dis29) - (buttonWidth / 2);
            endLocations[2][1] = ((screenHeight / 2) - (dis18 / 2)) - (buttonWidth / 2);
            endLocations[3][0] = ((screenWidth / 2) + dis29) - (buttonWidth / 2);
            endLocations[3][1] = ((screenHeight / 2) + (dis18 / 2)) - (buttonWidth / 2);
            endLocations[4][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[4][1] = ((screenHeight / 2) + dis18) - (buttonWidth / 2);
            endLocations[5][0] = ((screenWidth / 2) - dis29) - (buttonWidth / 2);
            endLocations[5][1] = ((screenHeight / 2) + (dis18 / 2)) - (buttonWidth / 2);
            endLocations[6][0] = ((screenWidth / 2) - dis29) - (buttonWidth / 2);
            endLocations[6][1] = ((screenHeight / 2) - (dis18 / 2)) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_8_1)) {
            int dis19 = (buttonWidth * 9) / 8;
            int dis210 = (int) (((double) (dis19 / 2)) * Math.sqrt(3.0d));
            endLocations[0][0] = ((screenWidth / 2) - dis19) - (buttonWidth / 2);
            endLocations[0][1] = ((screenHeight / 2) - dis210) - (buttonWidth / 2);
            endLocations[1][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[1][1] = ((screenHeight / 2) - dis210) - (buttonWidth / 2);
            endLocations[2][0] = ((screenWidth / 2) + dis19) - (buttonWidth / 2);
            endLocations[2][1] = ((screenHeight / 2) - dis210) - (buttonWidth / 2);
            endLocations[3][0] = ((screenWidth / 2) - (dis19 / 2)) - (buttonWidth / 2);
            endLocations[3][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[4][0] = ((screenWidth / 2) + (dis19 / 2)) - (buttonWidth / 2);
            endLocations[4][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[5][0] = ((screenWidth / 2) - dis19) - (buttonWidth / 2);
            endLocations[5][1] = ((screenHeight / 2) + dis210) - (buttonWidth / 2);
            endLocations[6][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[6][1] = ((screenHeight / 2) + dis210) - (buttonWidth / 2);
            endLocations[7][0] = ((screenWidth / 2) + dis19) - (buttonWidth / 2);
            endLocations[7][1] = ((screenHeight / 2) + dis210) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_8_2)) {
            int dis110 = (buttonWidth * 9) / 8;
            int dis211 = (int) (((double) (dis110 / 2)) * Math.sqrt(3.0d));
            endLocations[0][0] = ((screenWidth / 2) - dis211) - (buttonWidth / 2);
            endLocations[0][1] = ((screenHeight / 2) - dis110) - (buttonWidth / 2);
            endLocations[1][0] = ((screenWidth / 2) - dis211) - (buttonWidth / 2);
            endLocations[1][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[2][0] = ((screenWidth / 2) - dis211) - (buttonWidth / 2);
            endLocations[2][1] = ((screenHeight / 2) + dis110) - (buttonWidth / 2);
            endLocations[3][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[3][1] = ((screenHeight / 2) - (dis110 / 2)) - (buttonWidth / 2);
            endLocations[4][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[4][1] = ((screenHeight / 2) + (dis110 / 2)) - (buttonWidth / 2);
            endLocations[5][0] = ((screenWidth / 2) + dis211) - (buttonWidth / 2);
            endLocations[5][1] = ((screenHeight / 2) - dis110) - (buttonWidth / 2);
            endLocations[6][0] = ((screenWidth / 2) + dis211) - (buttonWidth / 2);
            endLocations[6][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[7][0] = ((screenWidth / 2) + dis211) - (buttonWidth / 2);
            endLocations[7][1] = ((screenHeight / 2) + dis110) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_8_3)) {
            int dis111 = (buttonWidth * 9) / 8;
            endLocations[0][0] = ((screenWidth / 2) - dis111) - (buttonWidth / 2);
            endLocations[0][1] = ((screenHeight / 2) - dis111) - (buttonWidth / 2);
            endLocations[1][0] = ((screenWidth / 2) - dis111) - (buttonWidth / 2);
            endLocations[1][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[2][0] = ((screenWidth / 2) - dis111) - (buttonWidth / 2);
            endLocations[2][1] = ((screenHeight / 2) + dis111) - (buttonWidth / 2);
            endLocations[3][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[3][1] = ((screenHeight / 2) - dis111) - (buttonWidth / 2);
            endLocations[4][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[4][1] = ((screenHeight / 2) + dis111) - (buttonWidth / 2);
            endLocations[5][0] = ((screenWidth / 2) + dis111) - (buttonWidth / 2);
            endLocations[5][1] = ((screenHeight / 2) - dis111) - (buttonWidth / 2);
            endLocations[6][0] = ((screenWidth / 2) + dis111) - (buttonWidth / 2);
            endLocations[6][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[7][0] = ((screenWidth / 2) + dis111) - (buttonWidth / 2);
            endLocations[7][1] = ((screenHeight / 2) + dis111) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_9_1)) {
            int dis112 = (buttonWidth * 9) / 8;
            endLocations[0][0] = ((screenWidth / 2) - dis112) - (buttonWidth / 2);
            endLocations[0][1] = ((screenHeight / 2) - dis112) - (buttonWidth / 2);
            endLocations[1][0] = ((screenWidth / 2) - dis112) - (buttonWidth / 2);
            endLocations[1][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[2][0] = ((screenWidth / 2) - dis112) - (buttonWidth / 2);
            endLocations[2][1] = ((screenHeight / 2) + dis112) - (buttonWidth / 2);
            endLocations[3][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[3][1] = ((screenHeight / 2) - dis112) - (buttonWidth / 2);
            endLocations[4][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[4][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[5][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[5][1] = ((screenHeight / 2) + dis112) - (buttonWidth / 2);
            endLocations[6][0] = ((screenWidth / 2) + dis112) - (buttonWidth / 2);
            endLocations[6][1] = ((screenHeight / 2) - dis112) - (buttonWidth / 2);
            endLocations[7][0] = ((screenWidth / 2) + dis112) - (buttonWidth / 2);
            endLocations[7][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[8][0] = ((screenWidth / 2) + dis112) - (buttonWidth / 2);
            endLocations[8][1] = ((screenHeight / 2) + dis112) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.CIRCLE_9_2)) {
            int dis113 = (int) (((double) ((buttonWidth * 8) / 8)) * Math.sqrt(2.0d));
            endLocations[0][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[0][1] = ((screenHeight / 2) - dis113) - (buttonWidth / 2);
            endLocations[1][0] = ((screenWidth / 2) - (dis113 / 2)) - (buttonWidth / 2);
            endLocations[1][1] = ((screenHeight / 2) - (dis113 / 2)) - (buttonWidth / 2);
            endLocations[2][0] = ((screenWidth / 2) + (dis113 / 2)) - (buttonWidth / 2);
            endLocations[2][1] = ((screenHeight / 2) - (dis113 / 2)) - (buttonWidth / 2);
            endLocations[3][0] = ((screenWidth / 2) - dis113) - (buttonWidth / 2);
            endLocations[3][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[4][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[4][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[5][0] = ((screenWidth / 2) + dis113) - (buttonWidth / 2);
            endLocations[5][1] = (screenHeight / 2) - (buttonWidth / 2);
            endLocations[6][0] = ((screenWidth / 2) - (dis113 / 2)) - (buttonWidth / 2);
            endLocations[6][1] = ((screenHeight / 2) + (dis113 / 2)) - (buttonWidth / 2);
            endLocations[7][0] = ((screenWidth / 2) + (dis113 / 2)) - (buttonWidth / 2);
            endLocations[7][1] = ((screenHeight / 2) + (dis113 / 2)) - (buttonWidth / 2);
            endLocations[8][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[8][1] = ((screenHeight / 2) + dis113) - (buttonWidth / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.HAM_1_1)) {
            endLocations[0][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[0][1] = (screenHeight / 2) - (buttonHeight / 2);
            return endLocations;
        } else if (placeType.equals(PlaceType.HAM_2_1)) {
            endLocations[0][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[0][1] = (screenHeight / 2) - buttonHeight;
            endLocations[1][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[1][1] = (screenHeight / 2) + buttonHeight;
            return endLocations;
        } else if (placeType.equals(PlaceType.HAM_3_1)) {
            endLocations[0][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[0][1] = (screenHeight / 2) - ((buttonHeight * 7) / 4);
            endLocations[1][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[1][1] = (screenHeight / 2) - (buttonHeight / 2);
            endLocations[2][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[2][1] = (screenHeight / 2) + ((buttonHeight * 3) / 4);
            return endLocations;
        } else if (placeType.equals(PlaceType.HAM_4_1)) {
            endLocations[0][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[0][1] = (screenHeight / 2) - ((buttonHeight * 23) / 10);
            endLocations[1][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[1][1] = (screenHeight / 2) - ((buttonHeight * 11) / 10);
            endLocations[2][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[2][1] = (screenHeight / 2) + (buttonHeight / 10);
            endLocations[3][0] = (screenWidth / 2) - (buttonWidth / 2);
            endLocations[3][1] = (screenHeight / 2) + ((buttonHeight * 13) / 10);
            return endLocations;
        } else {
            if (PlaceType.SHARE_3_1.v > placeType.v || placeType.v > PlaceType.SHARE_9_2.v) {
                return endLocations;
            }
            return getEndLocations(PlaceType.valueOf(placeType.v - (PlaceType.SHARE_3_1.v - PlaceType.CIRCLE_3_1.v)), screenWidth, screenHeight, buttonWidth, buttonWidth);
        }
    }
}
